name: ollama
services:
    ollama:
        build: .
        image: ollama-navi10
        devices:
            - /dev/kfd
            - /dev/dri
        volumes:
            - ollama:/root/.ollama
        ports:
            - 11434:11434
        container_name: ollama
volumes:
    ollama:
        name: ollama
